
project_id = "oelghoaiuvjhywlzldkt"

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.analyze-dream]
verify_jwt = false

[functions.generate-dream-image]
verify_jwt = true

[functions.send-flag-notification]
verify_jwt = true

[functions.upload-openai-image]
verify_jwt = true

[functions.dream-chat]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.sync-revenuecat-subscription]
verify_jwt = true

[functions.fetch-youtube-data]
verify_jwt = true

[functions.get-revenuecat-key]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.analyze-dream-symbols]
verify_jwt = true

[functions.analyze-character-image]
verify_jwt = true

[functions.compose-cinematic-prompt]
verify_jwt = false

[functions.compose-animation-prompt]
verify_jwt = true

[functions.generate-dream-video]
verify_jwt = true
